version: '{build}'  
image: 
  - Ubuntu
  - Visual Studio 2019

pull_requests:  
  do_not_increment_build_number: true

branches:
  only:
    - master
    - /v\d*\.\d*\.\d*/

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
nuget:  
  disable_publish_on_pr: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true  
  APPVEYOR_YML_DISABLE_PS_LINUX: true

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  - cmd: chmod +x build.sh

build_script:  
- ps: .\Build.ps1
- sh: ./build.sh

test: off  

artifacts:
- name: NuGet Packages
  path: ./artifacts/**/*.nupkg
- name: NuGet Symbol Packages
  path: ./artifacts/**/*.snupkg
- name: xUnit XML Test Results
  path: ./artifacts/**/*.xml
- name: xUnit HTML Test Results
  path: ./artifacts/**/*.html

for:
-
  matrix:
    only:
      - image: Ubuntu

  deploy:
  - provider: NuGet
    api_key:
      secure: 6JVLOhLqg0PBXEb5Ug98vPgKtXLSChdqZPol4ZB6bS5i4YeL58qPWucrVhoZobnL
    on:
      branch: master
      
  - provider: NuGet
    name: production
    api_key:
      secure: 6JVLOhLqg0PBXEb5Ug98vPgKtXLSChdqZPol4ZB6bS5i4YeL58qPWucrVhoZobnL
    on:
      APPVEYOR_REPO_TAG: true
