name: Pack workflow

on:
    workflow_run:
        workflows: [ "Build" ]
        types: [ requested ]
        branches: [ master ]

    workflow_dispatch:

env:
    BUILD_CONFIG: 'Release'
    DOTNET_VERSION: '6.x.x'
    PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && startsWith(github.ref, 'refs/tags/v') }}

jobs:   
    pack:
        runs-on: ubuntu-latest
        if: ${{ env.PUSH_PACKAGES }}
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
        - name: Determine version
          run: echo "VERSION = $(git describe --tags --dirty)" >> $GITHUB_ENV
        - name: Pack
          run: dotnet pack --output ./artifacts --configuration Release -p:Version=$VERSION
        - uses: actions/upload-artifact@v1
          with:
            name: artifacts
            path: ./artifacts