name: Pack workflow

on:
    workflow_run:
        workflows: [ "Build" ]
        types: [ requested ]
        branches: [ master ]

    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                required: true

env:
    BUILD_CONFIG: 'Release'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      push_packages: ${{ steps.check.outputs.push_packages }}
    steps:
      - id: check
        run: |
          echo "::set-output name=push_packages::${{ (github.event_name == 'push' && ((github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags'))) || (github.event_name == 'workflow_dispatch') }}"

  pack:
      if: ${{ needs.check.outputs.push_packages == 'true' }}
      runs-on: ubuntu-latest
      steps:
      - name: Determine version
        run: |
          echo "VERSION = $(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
          echo "$GITHUB_ENV"

      - name: 'Validate SemVer'
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          VERSION=${{ github.event.inputs.version }}
          if [[ ! "$VERSION" =~ ^([0-9]+\.){2}[0-9]+$ ]]; then
            echo "The version does not match the SemVer format (X.Y.Z). Please provide a valid version."
            exit 1
          else
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          fi

      - name: 'Print version'
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo 'Version: ${{ github.event.inputs.version }}'

      - name: Checkout
        uses: actions/checkout@v4
        with:
            lfs: true
            fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Pack
        run: |
          dotnet pack \
          --output ./artifacts \
          --configuration $BUILD_CONFIG \
          --version-suffix ${{ env.VERSION }}

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./artifacts
