name: Pack workflow

on:
    workflow_run:
        workflows: [ "Build" ]
        types: [ requested ]
        branches: [ master ]

    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                required: true

env:
    BUILD_CONFIG: 'Release'
    DOTNET_VERSION: '6.x.x'
    PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && startsWith(github.ref, 'refs/tags/v') }}

jobs:   
    pack:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3.0.0
          with:
              lfs: true
              fetch-depth: 0
        - name: Setup .NET
          uses: actions/setup-dotnet@v2.0.0
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
        - name: Determine version
          run: |
                echo "VERSION = $(git describe --tags --dirty)" >> $GITHUB_ENV
                echo "${{GITHUB_REF:10}}"
                echo "${{GITHUB_ENV}}"
        -   name: 'Print version'
            if: ${{ github.event_name == 'workflow_dispatch' }}
            run: |
                echo 'Version: ${{ github.event.inputs.version }}'
        - name: Pack
          run: dotnet pack --output ./artifacts --configuration $BUILD_CONFIG --version-suffix github.event.inputs.version
        - uses: actions/upload-artifact@v2.3.1
          with:
            name: artifacts
            path: ./artifacts