name: Publish workflow

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  
env:
    BUILD_CONFIG: 'Release'
    DOTNET_VERSION: '6.x.x'
    PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && startsWith(github.ref, 'refs/tags/v') }}

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: pack
    if: ${{ env.PUSH_PACKAGES }}
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - uses: actions/download-artifact@v1
      with:
        name: artifacts
        path: ./artifacts
        
    - name: Publish packages
      run: dotnet nuget push ./artifacts/**.nupkg --source nuget.org --api-key ${{secrets.NUGET_TOKEN}}
