name: Publish workflow

on:
    workflow_run:
        workflows: [ "Build" ]
        types: [ requested ]
        branches: [ master ]

    workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest
    needs: pack

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: ./artifacts

    - name: Publish packages
      run: |
        dotnet nuget push ./artifacts/**.nupkg \
        --source https://api.nuget.org/v3/index.json \
        --api-key ${{secrets.NUGET_TOKEN}} \
        --skip-duplicate \
