name: Publish workflow

on:
    workflow_run:
        workflows: [ "Build" ]
        types: [ requested ]
        branches: [ master ]

    workflow_dispatch:

env:
    BUILD_CONFIG: 'Release'
    PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && startsWith(github.ref, 'refs/tags/v') }}

jobs:
  publish:

    runs-on: ubuntu-latest
    needs: pack
    if: ${{ env.PUSH_PACKAGES }}
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: ./artifacts

    - name: Publish packages
      run: |
        dotnet nuget push ./artifacts/**.nupkg \
        --source https://api.nuget.org/v3/index.json \
        --api-key ${{secrets.NUGET_TOKEN}} \
        --skip-duplicate \
